=== DanijelCBS/sciXiv/sciXiv/target/classes/static/xmlSchemas/notification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/notification" xmlns:nt="http://ftn.uns.ac.rs/notification">

    <xs:element name="notification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sender" type="nt:TParticipant"/>
                <xs:element name="reciever" type="nt:TParticipant"/>
                <xs:element name="publicationName" type="xs:string"/>
                <xs:element name="notificationType" type="nt:TNotificationType"/>
                <xs:element name="content" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="date" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TNotificationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="publication submitted"/>
            <xs:enumeration value="publication withdrew"/>
            <xs:enumeration value="review assigned"/>
            <xs:enumeration value="review submitted"/>
            <xs:enumeration value="publication accepted"/>
            <xs:enumeration value="publication rejected"/>
            <xs:enumeration value="revision requested"/>
            <xs:enumeration value="revision submitted"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="TParticipant">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="role">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="author"/>
                        <xs:enumeration value="reviewer"/>
                        <xs:enumeration value="editor"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/examples/instanceNotification.xml
<?xml version="1.0" encoding="UTF-8"?>
<notification xmlns="http://ftn.uns.ac.rs/notification"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/notification file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/notification.xsd" date="2006-05-04">
    <sender>
        <name>Gvido od Areca</name>
        <role>author</role>
        <email>nestosedesilo@gmail.com</email>
    </sender>
    <reciever>
        <name>Semso od Areca</name>
        <role>author</role>
        <email>nestosezbiva@gmail.com</email>
    </reciever>
    <publicationName>publicationName0</publicationName>
    <notificationType>publication submitted</notificationType>
    <content>Nam id pretium tortor, vel condimentum urna. Maecenas vestibulum vehicula tincidunt. Vestibulum rutrum dui condimentum nisl elementum, ac semper magna aliquam. Proin sed porttitor turpis, at fringilla eros. Nam sagittis leo et pharetra pretium. In hac habitasse platea dictumst. In consectetur maximus lorem, eu ullamcorper felis hendrerit iaculis. 
    </content>
</notification>
