=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/coverLetter" xmlns:cl="http://ftn.uns.ac.rs/coverLetter">
    <xs:element name="coverLetter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="publicationTitle" type="xs:string"/>
                <xs:element minOccurs="0" name="version" type="xs:positiveInteger"/>
                <xs:element name="author">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="educationTitle" type="xs:string"/>
                            <xs:element name="affiliation" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="state" type="xs:string"/>
                            <xs:element minOccurs="0" name="phoneNumber" type="xs:string"/>
                            <xs:element minOccurs="0" name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="signature" type="xs:base64Binary"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="targetPublisher" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="editor" type="xs:string"/>
                            <xs:element name="journal" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="content">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element maxOccurs="unbounded" name="paragraph">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="boldText" type="xs:string"/>
                                        <xs:element name="emphasizedText" type="xs:string"/>
                                        <xs:element name="quote">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="source" type="xs:string"/>
                                                  <xs:element name="quoteContent" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="list">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="listItem"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute default="false" name="ordered"
                                                  type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="submissionDate" type="xs:date"/>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/HOGmethod_cl_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>HOG method</publicationTitle>
    <version>1</version>
    <author>
        <name>John Bosnich</name>
        <educationTitle>MSc</educationTitle>
        <affiliation>ETF</affiliation>
        <city>Belgrade</city>
        <state>Serbia</state>
        <phoneNumber>003871245712578</phoneNumber>
        <email>bosnich@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>National Geographic</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Optical Music Recognition</boldText>
            <emphasizedText>Optical Music Recognition is a field of research that investigates how to computationally
                decode music notation from images. Despite the efforts made so far, there are hardly any complete
                solutions to the problem. In this work, we study the use of neural networks that work in an end-to-end
                manner. This is achieved by using a neural model that combines the capabilities of convolutional
                neural networks, which work on the input image, and recurrent neural networks, which deal with
                the sequential nature of the problem. Thanks to the use of the the so-called Connectionist Temporal
                Classification loss function, these models can be directly trained from input images accompanied by
                their corresponding transcripts into music symbol sequences. We also present the Printed Images
                of Music Staves (PrIMuS) dataset, containing more than 80,000 monodic single-staff real scores in
                common western notation, that is used to train and evaluate the neural approach. In our experiments,
                it is demonstrated that this formulation can be carried out successfully. Additionally, we study several
                considerations about the codification of the output musical sequences, the convergence and scalability
                of the neural models, as well as the ability of this approach to locate symbols in the input score.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>I have self-doubt. I have insecurity. I have fear of failure. I have nights when I show up at the arena and I'm like, 'My back hurts, my feet 
                    hurt, my knees hurt. I don't have it. I just want to chill.' We all have self-doubt. You don't deny it, but you also don't capitulate to it. You embrace it.
                </quoteContent>
            </quote>
            <list ordered="true">
                <listItem>HOG method</listItem>
                <listItem>Computer Vision</listItem>
            </list>
            <boldText>OMR for CWMN</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
                Then, the staff can be addressed as a single unit instead of considering it as a sequence of isolated
                elements that have to be detected and recognized independently. This also opens the possibility
                to boost the optical recognition by taking into account the musical context which, in spite of being
                extremely difficult to model entirely, can certainly help in the process. Thus, it seems interesting to
                tackle the OMR task over single staves in an holistic fashion, in which the expected output is directly
                the sequence of musical symbols present in the image.</emphasizedText>
            <quote>
                <source>Buddha</source>
                <quoteContent>Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Old-fashioned CV</listItem>
                <listItem>Optimizations of existing methods</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>Using the gradient direction to reduce the number of votes</boldText>
            <emphasizedText>An improvement suggested by O'Gorman and Clowes can be used to detect lines if one takes into account that the local gradient of the image 
                intensity will necessarily be orthogonal to the edge. Since edge detection generally involves computing the intensity gradient magnitude, the gradient 
                direction is often found as a side effect. If a given point of coordinates (x,y) happens to indeed be on a line, then the local direction of the gradient 
                gives the θ parameter corresponding to said line, and the r parameter is then immediately obtained. (Shapiro and Stockman, 305) The gradient direction can be 
                estimated to within 20°, which shortens the sinusoid trace from the full 180° to roughly 45°. This reduces the computation time and has the interesting effect
                of reducing the number of useless votes, thus enhancing the visibility of the spikes corresponding to real lines in the image.</emphasizedText>
            <quote>
                <source>Aristotle</source>
                <quoteContent>It is during our darkest moments that we must focus to see the light.</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Hough transform</listItem>
                <listItem>Image transforming</listItem>
            </list>
            <boldText>Hough transform of curves, and its generalization for analytical and non-analytical shapes
            </boldText>
            <emphasizedText>Although the version of the transform described above applies only to finding straight lines, a similar transform can be used for finding any shape 
                which can be represented by a set of parameters. A circle, for instance, can be transformed into a set of three parameters, representing its center and radius,
                so that the Hough space becomes three dimensional. Arbitrary ellipses and curves can also be found this way, as can any shape easily expressed as a set of 
                parameters.
                
                The generalization of the Hough transform for detecting analytical shapes in spaces having any dimensionality was proposed by Fernandes and Oliveira.[11] In 
                contrast to other Hough transform-based approaches for analytical shapes, Fernandes' technique does not depend on the shape one wants to detect nor on the 
                input data type. The detection can be driven to a type of analytical shape by changing the assumed model of geometry where data have been encoded (e.g., 
                euclidean space, projective space, conformal geometry, and so on), while the proposed formulation remains unchanged. Also, it guarantees that the intended 
                shapes are represented with the smallest possible number of parameters, and it allows the concurrent detection of different kinds of shapes that best fit an 
                input set of entries with different dimensionalities and different geometric definitions (e.g., the concurrent detection of planes and spheres that best fit 
                a set of points, straight lines and circles).
                
                For more complicated shapes in the plane (i.e., shapes that cannot be represented analytically in some 2D space), the Generalised Hough transform [12] is used,
                which allows a feature to vote for a particular position, orientation and/or scaling of the shape using a predefined look-up table.
                
            </emphasizedText>

            <list ordered="true">
                <listItem>Circle detection process</listItem>
                <listItem>Detection of 3D objects</listItem>
            </list>
        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/examples/instanceCoverLetter.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>publicationTitle0</publicationTitle>
    <version>50</version>
    <author>
        <name>Ian Goodfellow</name>
        <educationTitle>phD</educationTitle>
        <affiliation>Apple</affiliation>
        <city>Los Angeles</city>
        <state>California, USA</state>
        <phoneNumber>12948824895325779</phoneNumber>
        <email>iangoodfellow@apple.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Machine Learning</editor>
        <journal>Apple AI journal</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Ovo je boldovan tekst.</boldText>
            <emphasizedText>Ovo je emphasized tekst.</emphasizedText>
            <quote>
                <source>Nikola Zubic</source>
                <quoteContent>Stize AI, ne plasite se braco, sve cemo mi to kroz mreze da propustimo. Neka bude feed-forward propagacija neprestana, nek se ori aktivacija za aktivacijom.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Jabuka</listItem>
                <listItem>Kruska</listItem>
            </list>
            <boldText>Boldovani tekst..</boldText>
            <emphasizedText>Emphasized tekst...</emphasizedText>
            <quote>
                <source>Izvor</source>
                <quoteContent>Evo citira se nesto iz izvora</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Nije ordered</listItem>
                <listItem>Sta da se radi</listItem>
            </list>
        </paragraph>
        <paragraph>
        <boldText>boldText2</boldText>
        <emphasizedText>emphasizedText2</emphasizedText>
        <quote>
            <source>source2</source>
            <quoteContent>quoteContent2</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Ordered je</listItem>
                <listItem>Svi srecni</listItem>
            </list>
            <boldText>boldText3</boldText>
            <emphasizedText>emphasizedText3</emphasizedText>
            <quote>
                <source>source3</source>
                <quoteContent>quoteContent3</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>listItem6</listItem>
                <listItem>listItem7</listItem>
            </list>
        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/MusicalApplicationsUsingXML_cl_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Musical Applications Using XML</publicationTitle>
    <version>1</version>
    <author>
        <name>Roland, P</name>
        <educationTitle>phD</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>252362362362362</phoneNumber>
        <email>rol@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>PLOS ONE</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Musical notation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>I focus on one thing and one thing only - that's trying to win as many championships as I can.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>XML</listItem>
                <listItem>Musical OMR</listItem>
            </list>
            <boldText>Image processing with usage of XML data</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
                Then, the staff can be addressed as a single unit instead of considering it as a sequence of isolated
                elements that have to be detected and recognized independently. This also opens the possibility
                to boost the optical recognition by taking into account the musical context which, in spite of being
                extremely difficult to model entirely, can certainly help in the process. Thus, it seems interesting to
                tackle the OMR task over single staves in an holistic fashion, in which the expected output is directly
                the sequence of musical symbols present in the image.</emphasizedText>
            <quote>
                <source>Walt Whitman</source>
                <quoteContent>Keep your face always toward the sunshine - and shadows will fall behind you.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>History</listItem>
                <listItem>Support</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>History</boldText>
            <emphasizedText>MusicXML was invented by Michael Good and initially developed by Recordare LLC. It derived several key concepts from existing academic formats 
                (such as Walter Hewlett's MuseData and David Huron's Humdrum). It is designed for the interchange of scores, particularly between different scorewriters. 
                MusicXML development was managed by MakeMusic following the company's acquisition of Recordare in 2011.[6][7] MusicXML development was transferred to the 
                W3C Music Notation Community Group in July 2015.[8] 
                Version 1.0 was released in January 2004. Version 1.1 was released in May 2005 with improved formatting support. Version 2.0 was released in June 2007 
                and included a standard compressed format.[9] All of these versions were defined by a series of document type definitions (DTDs). An XML Schema Definition 
                (XSD) implementation of Version 2.0 was released in September 2008. Version 3.0 was released in August 2011 with improved virtual instrument support, in 
                both DTD and XSD versions.[10][11] Version 3.1 was released in December 2017 with improved support for the Standard Music Font Layout (SMuFL).[3] The MusicXML
                DTDs and XSDs are each freely redistributable under the W3C Community Final Specification Agreement.[5]</emphasizedText>
            <quote>
                <source>Mahatma Gandhi</source>
                <quoteContent>In a gentle way, you can shake the world.</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>DTD</listItem>
                <listItem>XSD</listItem>
            </list>
            <boldText>Example</boldText>
            <emphasizedText>Like all XML-based formats, MusicXML is intended to be easy for automated tools to parse and manipulate. Though it is possible to create MusicXML
                by hand, interactive score writing programs like Finale and MuseScore greatly simplify the reading, writing, and modifying of MusicXML files. 
                The following example is a score consisting of a single whole note middle C in the key of C major on the Treble Clef.[16]</emphasizedText>

        </paragraph>
    </content>
</coverLetter>
