=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/coverLetter" xmlns:cl="http://ftn.uns.ac.rs/coverLetter">
    <xs:element name="coverLetter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="publicationTitle" type="xs:string"/>
                <xs:element minOccurs="0" name="version" type="xs:positiveInteger"/>
                <xs:element name="author">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="educationTitle" type="xs:string"/>
                            <xs:element name="affiliation" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="state" type="xs:string"/>
                            <xs:element minOccurs="0" name="phoneNumber" type="xs:string"/>
                            <xs:element minOccurs="0" name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="signature" type="xs:base64Binary"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="targetPublisher" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="editor" type="xs:string"/>
                            <xs:element name="journal" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="content">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element maxOccurs="unbounded" name="paragraph">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="boldText" type="xs:string"/>
                                        <xs:element name="emphasizedText" type="xs:string"/>
                                        <xs:element name="quote">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="source" type="xs:string"/>
                                                  <xs:element name="quoteContent" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="list">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="listItem"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute default="false" name="ordered"
                                                  type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="submissionDate" type="xs:date"/>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/NeuralNetworks_cl_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Neural networks</publicationTitle>
    <version>1</version>
    <author>
        <name>Pero Peric</name>
        <educationTitle>phD</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>12959327956727836</phoneNumber>
        <email>pero@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>Scientifica Noevica</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Motivation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>My parents are my backbone. Still are. They're the only group that will support you if you score zero or you score 40.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Neural networks</listItem>
                <listItem>Machine Learning</listItem>
                <listItem>Deep Learning</listItem>
            </list>
            <boldText>Motivation and about publication</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
                Then, the staff can be addressed as a single unit instead of considering it as a sequence of isolated
                elements that have to be detected and recognized independently. This also opens the possibility
                to boost the optical recognition by taking into account the musical context which, in spite of being
                extremely difficult to model entirely, can certainly help in the process. Thus, it seems interesting to
                tackle the OMR task over single staves in an holistic fashion, in which the expected output is directly
                the sequence of musical symbols present in the image.</emphasizedText>
            <quote>
                <source>Walt Whitman</source>
                <quoteContent>We convince by our presence.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Quantum AI</listItem>
                <listItem>Possibilities of new approaches</listItem>
                <listItem>AI and physics</listItem>
            </list>
            <boldText>Organization</boldText>
            <emphasizedText>The neurons are typically organized into multiple layers, especially in deep learning. Neurons of one layer connect only to neurons of the 
                immediately preceding and immediately following layers. The layer that receives external data is the input layer. The layer that produces the ultimate
                result is the output layer. In between them are zero or more hidden layers. Single layer and unlayered networks are also used. Between two layers, multiple
                connection patterns are possible. They can be fully connected, with every neuron in one layer connecting to every neuron in the next layer. They can be
                pooling, where a group of neurons in one layer connect to a single neuron in the next layer, thereby reducing the number of neurons in that layer.[43]
                Neurons with only such connections form a directed acyclic graph and are known as feedforward networks.[44] Alternatively, networks that allow connections 
                between neurons in the same or previous layers are known as recurrent networks.[45]
            </emphasizedText>
            <quote>
                <source>Lao Tzu</source>
                <quoteContent>Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend. Non-being is the greatest joy.
                </quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Hyperparameter</listItem>
                <listItem>Learning</listItem>
                <listItem>Learning rates</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>Hyperparameter</boldText>
            <emphasizedText>A hyperparameter is a constant parameter whose value is set before the learning process begins. The values of parameters are derived via learning. 
                Examples of hyperparameters include learning rate, the number of hidden layers and batch size.[46] The values of some hyperparameters can be dependent on
                those of other hyperparameters. For example, the size of some layers can depend on the overall number of layers.
            </emphasizedText>
            <quote>
                <source>Audrey Hepburn</source>
                <quoteContent>I believe in pink. I believe that laughing is the best calorie burner. I believe in kissing, kissing a lot. I believe in being strong
                    when everything seems to be going wrong. I believe that happy girls are the prettiest girls. I believe that tomorrow is another day and I believe 
                    in miracles.</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>RNN</listItem>
                <listItem>CNN</listItem>
                <listItem>LSTM</listItem>
            </list>
            <boldText>Backpropagation</boldText>
            <emphasizedText>Backpropagation is a method to adjust the connection weights to compensate for each error found during learning. The error amount 
                is effectively divided among the connections. Technically, backprop calculates the gradient (the derivative) of the cost function associated with a 
                given state with respect to the weights. The weight updates can be done via stochastic gradient descent or other methods, such as Extreme
                Learning Machines,[48] "No-prop" networks,[49] training without backtracking,[50] "weightless" networks,[51][52] and non-connectionist neural networks.
                
            </emphasizedText>
            <quote>
                <source>Earl N.</source>
                <quoteContent>All you need is the plan, the road map, and the courage to press on to your destination.</quoteContent>
            </quote>
        </paragraph>
        
        <paragraph>
            <boldText>Network design</boldText>
            <emphasizedText>Neural architecture search (NAS) uses machine learning to automate ANN design. Various approaches to NAS have designed networks that compare
                well with hand-designed systems. The basic search algorithm is to propose a candidate model, evaluate it against a dataset and use the results as feedback
                to teach the NAS network.[80] Available systems include AutoML and AutoKeras.[81]
                
                Design issues include deciding the number, type and connectedness of network layers, as well as the size of each and the connection type (full, pooling, ...).
                
                Hyperparameters must also be defined as part of the design (they are not learned), governing matters such as how many neurons are in each layer,
                learning rate, step, stride, depth, receptive field and padding (for CNNs), etc.[82]
                
            </emphasizedText>
        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/SoftComputing_cl_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Soft computing</publicationTitle>
    <version>1</version>
    <author>
        <name>Pero Peric</name>
        <educationTitle>MSc</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>524623623463454335</phoneNumber>
        <email>pero@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>Nature Communications</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Main motivation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>At the end of 2003, my game was complete. Shooting, defense, using the dribble, transition, midrange stuff was all there. Then it was about 
                    fine-tuning and trying to improve in each area.
                </quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Primitive CV</listItem>
                <listItem>CV with usage of Deep Learning</listItem>
            </list>
            <boldText>Main content</boldText>
            <emphasizedText>            
                We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
                Then, the staff can be addressed as a single unit instead of considering it as a sequence of isolated
                elements that have to be detected and recognized independently. This also opens the possibility
                to boost the optical recognition by taking into account the musical context which, in spite of being
                extremely difficult to model entirely, can certainly help in the process. Thus, it seems interesting to
                tackle the OMR task over single staves in an holistic fashion, in which the expected output is directly
                the sequence of musical symbols present in the image.
            </emphasizedText>
            <quote>
                <source>Khalil Gibran</source>
                <quoteContent>Yesterday we obeyed kings and bent our necks before emperors. But today we kneel only to truth, follow only beauty, and obey only love.
                </quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Fuzzy logic</listItem>
                <listItem>Evolutionary computation</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>Fuzzy logic</boldText>
            <emphasizedText>Fuzzification is the process of assigning the numerical input of a system to fuzzy sets with some degree of membership. This degree of 
                membership may be anywhere within the interval [0,1]. If it is 0 then the value does not belong to the given fuzzy set, and if it is 1 then the value 
                completely belongs within the fuzzy set. Any value between 0 and 1 represents the degree of uncertainty that the value belongs in the set. These fuzzy
                sets are typically described by words, and so by assigning the system input to fuzzy sets, we can reason with it in a linguistically natural manner.
            </emphasizedText>

            <list ordered="true">
                <listItem>AND(x,y)</listItem>
                <listItem>OR(x,y)</listItem>
            </list>
            <boldText>History</boldText>
            <emphasizedText>Simulations of evolution using evolutionary algorithms and artificial life started with the work of Nils Aall Barricelli in the 1960s, and 
                was extended by Alex Fraser, who published a series of papers on simulation of artificial selection.[1] Artificial evolution became a widely recognised 
                optimisation method as a result of the work of Ingo Rechenberg in the 1960s and early 1970s, who used evolution strategies to solve complex engineering
                problems.[2] Genetic algorithms in particular became popular through the writing of John Holland.[3] As academic interest grew, dramatic increases in the 
                power of computers allowed practical applications, including the automatic evolution of computer programs.[4] Evolutionary algorithms are now used to solve
                multi-dimensional problems more efficiently than software produced by human designers, and also to optimise the design of systems.[5][6]
                
            </emphasizedText>

        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/ImageProcessing_cl_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Image processing</publicationTitle>
    <version>1</version>
    <author>
        <name>Ziko Zikic</name>
        <educationTitle>Professor Emeritus GodFather</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>003852185281785</phoneNumber>
        <email>ziko@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>Scientific NovoSadian</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Main motivation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Muhammad Ali</source>
                <quoteContent>I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Medical imaging</listItem>
                <listItem>Military Computer Vision</listItem>
            </list>
            <boldText>Image sensors</boldText>
            <emphasizedText>Many of the techniques of digital image processing, or digital picture processing as it often was called, were developed in the 1960s, at Bell
                Laboratories, the Jet Propulsion Laboratory, Massachusetts Institute of Technology, University of Maryland, and a few other research facilities,
                with application to satellite imagery, wire-photo standards conversion, medical imaging, videophone, character recognition, and photograph enhancement.[3] 
                The purpose of early image processing was to improve the quality of the image. It was aimed for human beings to improve the visual effect of people. In 
                image processing, the input is a low-quality image, and the output is an image with improved quality. Common image processing include image enhancement, 
                restoration, encoding, and compression. The first successful application was the American Jet Propulsion Laboratory (JPL). They used image processing 
                techniques such as geometric correction, gradation transformation, noise removal, etc. on the thousands of lunar photos sent back by the Space Detector 
                Ranger 7 in 1964, taking into account the position of the sun and the environment of the moon. The impact of the successful mapping of the moon's surface
                map by the computer has been a huge success. Later, more complex image processing was performed on the nearly 100,000 photos sent back by the spacecraft,
                so that the topographic map, color map and panoramic mosaic of the moon were obtained, which achieved extraordinary results and laid a solid foundation
                for human landing on the moon.[4]
                
                The cost of processing was fairly high, however, with the computing equipment of that era. That changed in the 1970s, when digital image processing 
                proliferated as cheaper computers and dedicated hardware became available. This led to images being processed in real-time, for some dedicated problems 
                such as television standards conversion. As general-purpose computers became faster, they started to take over the role of dedicated hardware for all but 
                the most specialized and computer-intensive operations. With the fast computers and signal processors available in the 2000s, digital image processing 
                has become the most common form of image processing, and is generally used because it is not only the most versatile method, but also the cheapest.
                
            </emphasizedText>
        </paragraph>
        
        <paragraph>
            <boldText>Image compression</boldText>
            <emphasizedText>An important development in digital image compression technology was the discrete cosine transform (DCT), a lossy compression technique first 
                proposed by Nasir Ahmed in 1972.[14] DCT compression became the basis for JPEG, which was introduced by the Joint Photographic Experts Group in 1992.[15]
                JPEG compresses images down to much smaller file sizes, and has become the most widely used image file format on the Internet.[16] Its highly efficient 
                DCT compression algorithm was largely responsible for the wide proliferation of digital images and digital photos,[17] with several billion JPEG images 
                produced every day as of 2015.[18]
                
            </emphasizedText>

            <boldText>Medical imaging</boldText>
            <emphasizedText>In 1972, the engineer from British company EMI Housfield invented the X-ray computed tomography device for head diagnosis, 
                which is what we usually called CT(Computer Tomography). The CT nucleus method is based on the projection of the human head section and
                is processed by computer to reconstruct the cross-sectional image, which is called image reconstruction. In 1975, EMI successfully 
                developed a CT device for the whole body, which obtained a clear tomographic image of various parts of the human body. In 1979, this
                diagnostic technique won the Nobel Prize.[4] Digital image processing technology for medical applications was inducted into the Space
                Foundation Space Technology Hall of Fame in 1994.[24]
                
            </emphasizedText>

            <list ordered="true">
                <listItem>Simple IP</listItem>
                <listItem>Complex IP</listItem>
            </list>
            
        </paragraph>
    </content>
</coverLetter>
