=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://ftn.uns.ac.rs/coverLetter" xmlns:cl="http://ftn.uns.ac.rs/coverLetter">
    <xs:element name="coverLetter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="publicationTitle" type="xs:string"/>
                <xs:element minOccurs="0" name="version" type="xs:positiveInteger"/>
                <xs:element name="author">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="educationTitle" type="xs:string"/>
                            <xs:element name="affiliation" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                            <xs:element name="state" type="xs:string"/>
                            <xs:element minOccurs="0" name="phoneNumber" type="xs:string"/>
                            <xs:element minOccurs="0" name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="signature" type="xs:base64Binary"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="targetPublisher" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="editor" type="xs:string"/>
                            <xs:element name="journal" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="content">
                    <xs:complexType>
                        <xs:sequence maxOccurs="1" minOccurs="1">
                            <xs:element maxOccurs="unbounded" name="paragraph">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded" minOccurs="0">
                                        <xs:element name="boldText" type="xs:string"/>
                                        <xs:element name="emphasizedText" type="xs:string"/>
                                        <xs:element name="quote">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="source" type="xs:string"/>
                                                  <xs:element name="quoteContent" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="list">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="listItem"
                                                  type="xs:string"/>
                                                </xs:sequence>
                                                <xs:attribute default="false" name="ordered"
                                                  type="xs:boolean"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="submissionDate" type="xs:date"/>
            <xs:attribute name="id" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/SoftComputing_cl_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Soft computing</publicationTitle>
    <version>2</version>
    <author>
        <name>Pero Peric</name>
        <educationTitle>MSc</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>524623623463454335</phoneNumber>
        <email>pero@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>Nature Communications</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Main motivation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>At the end of 2003, my game was complete. Shooting, defense, using the dribble, transition, midrange stuff was all there. Then it was about 
                    fine-tuning and trying to improve in each area.
                </quoteContent>
            </quote>
            <list ordered="true">
                <listItem>Primitive CV</listItem>
                <listItem>CV with usage of Deep Learning</listItem>
            </list>
            <boldText>Main content</boldText>
            <emphasizedText>            
                We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
                Then, the staff can be addressed as a single unit instead of considering it as a sequence of isolated
                elements that have to be detected and recognized independently. This also opens the possibility
                to boost the optical recognition by taking into account the musical context which, in spite of being
                extremely difficult to model entirely, can certainly help in the process. Thus, it seems interesting to
                tackle the OMR task over single staves in an holistic fashion, in which the expected output is directly
                the sequence of musical symbols present in the image.
            </emphasizedText>
            <quote>
                <source>Khalil Gibran</source>
                <quoteContent>Yesterday we obeyed kings and bent our necks before emperors. But today we kneel only to truth, follow only beauty, and obey only love.
                </quoteContent>
            </quote>
            <list ordered="false">
                <listItem>Genetic algorithm</listItem>
                <listItem>Differential evolution</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>Genetic algorithm</boldText>
            <emphasizedText>In a genetic algorithm, a population of candidate solutions (called individuals, creatures, or phenotypes) to an optimization problem is evolved 
                toward better solutions. Each candidate solution has a set of properties (its chromosomes or genotype) which can be mutated and altered; traditionally,
                solutions are represented in binary as strings of 0s and 1s, but other encodings are also possible.[3]
                
                The evolution usually starts from a population of randomly generated individuals, and is an iterative process, with the population in each iteration 
                called a generation. In each generation, the fitness of every individual in the population is evaluated; the fitness is usually the value of the objective
                function in the optimization problem being solved. The more fit individuals are stochastically selected from the current population, and each individual's 
                genome is modified (recombined and possibly randomly mutated) to form a new generation. The new generation of candidate solutions is then used in the next 
                iteration of the algorithm. Commonly, the algorithm terminates when either a maximum number of generations has been produced, or a satisfactory fitness level
                has been reached for the population.
                
            </emphasizedText>

            <list ordered="true">
                <listItem>AND(x,y)</listItem>
                <listItem>OR(x,y)</listItem>
            </list>
            <boldText>Differential evolution</boldText>
            <emphasizedText>In evolutionary computation, differential evolution (DE) is a method that optimizes a problem by iteratively trying to improve a candidate 
                solution with regard to a given measure of quality. Such methods are commonly known as metaheuristics as they make few or no assumptions about the problem 
                being optimized and can search very large spaces of candidate solutions. However, metaheuristics such as DE do not guarantee an optimal solution is ever found.
                
                DE is used for multidimensional real-valued functions but does not use the gradient of the problem being optimized, which means DE does not require the 
                optimization problem to be differentiable, as is required by classic optimization methods such as gradient descent and quasi-newton methods. DE can therefore 
                also be used on optimization problems that are not even continuous, are noisy, change over time, etc.[1]
            </emphasizedText>

        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/xmlSchemas/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>publicationTitle0</publicationTitle>
    <version>50</version>
    <author>
        <name>name0</name>
        <educationTitle>educationTitle0</educationTitle>
        <affiliation>affiliation0</affiliation>
        <city>city0</city>
        <state>state0</state>
        <phoneNumber>phoneNumber0</phoneNumber>
        <email> @ .a</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>editor0</editor>
        <journal>journal0</journal>
    </targetPublisher>
    <content>
        <paragraph>
<!--            <boldText>boldText0</boldText>-->
<!--            <emphasizedText>emphasizedText0</emphasizedText>-->
<!--            <quote>
                <source>source0</source>
                <quoteContent>quoteContent0</quoteContent>
            </quote>-->
            <list ordered="false">
                <listItem>listItem0</listItem>
                <listItem>listItem1</listItem>
            </list>
            <boldText>boldText1</boldText>
<!--            <emphasizedText>emphasizedText1</emphasizedText>-->
<!--            <quote>
                <source>source1</source>
                <quoteContent>quoteContent1</quoteContent>
            </quote>-->
<!--            <list ordered="false">
                <listItem>listItem2</listItem>
                <listItem>listItem3</listItem>
            </list>-->
        </paragraph>
        <paragraph>
<!--            <boldText>boldText2</boldText>-->
<!--            <emphasizedText>emphasizedText2</emphasizedText>-->
<!--            <quote>
                <source>source2</source>
                <quoteContent>quoteContent2</quoteContent>
            </quote>-->
            <list ordered="false">
                <listItem>listItem4</listItem>
                <listItem>listItem5</listItem>
            </list>
            <boldText>boldText3</boldText>
<!--            <emphasizedText>emphasizedText3</emphasizedText>-->
<!--            <quote>
                <source>source3</source>
                <quoteContent>quoteContent3</quoteContent>
            </quote>-->
<!--            <list ordered="false">
                <listItem>listItem6</listItem>
                <listItem>listItem7</listItem>
            </list>-->
        </paragraph>
    </content>
</coverLetter>

=== DanijelCBS/sciXiv/Backend/src/main/resources/static/examples/coverLetters/MusicalApplicationsUsingXML_cl_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<coverLetter xmlns="http://ftn.uns.ac.rs/coverLetter"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://ftn.uns.ac.rs/coverLetter file:/C:/Users/Nikola%20Zubic/Desktop/XMLWEB/sciXiv/Backend/src/main/resources/static/xmlSchemas/coverLetter.xsd" submissionDate="2006-05-04" id="id1">
    <publicationTitle>Musical Applications Using XML</publicationTitle>
    <version>2</version>
    <author>
        <name>Roland, P</name>
        <educationTitle>phD</educationTitle>
        <affiliation>FTN</affiliation>
        <city>Novi Sad</city>
        <state>Serbia</state>
        <phoneNumber>252362362362362</phoneNumber>
        <email>rol@gmail.com</email>
        <signature>ZGVmYXVsdA==</signature>
    </author>
    <targetPublisher>
        <editor>Mihajlo Kusljic</editor>
        <journal>PLOS ONE</journal>
    </targetPublisher>
    <content>
        <paragraph>
            <boldText>Musical notation</boldText>
            <emphasizedText>We believe that the problem to progress in OMR for CWMN lies in the complexity involved in
                correctly modeling the composition of musical symbols. Unlike these hand-engineered multi-stage
                approaches, we propose a holistic strategy in which the musical notation is learned as a whole using
                machine learning strategies. However, to reduce the complexity to a feasible level, we do consider
                a first initial stage in which the image is pre-processed to find and separate the different staves of the
                score. Staves are good basic units to work on, analogously to similar text recognition where a single
                line of text is assumed as input unit. Note that this is not a strong assumption as there are successful
                algorithms for isolating staves, as mentioned above.
            </emphasizedText>
            <quote>
                <source>Kobe Bryant</source>
                <quoteContent>I focus on one thing and one thing only - that's trying to win as many championships as I can.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>XML</listItem>
                <listItem>Musical OMR</listItem>
            </list>
            <boldText>SMDL</boldText>
            <emphasizedText>Several attempts to address this unfortunate situation have beenmade, chief among which are the Notation Interchange File Format (NIFF)and the 
                Standard Music Description Language (SMDL). NIFF was completedin 1995 and was designed specifically as a music-notation interchangestandard. Even though it
                has been adopted by several notation andmusic-scanning programs, its graphical approach to representing musicinformation limits its usefulness for performance 
                applications. WhileSMDL has reached the status of official standard (ISO/IEC DraftInternational Standard 10743), it suffers from the opposite extreme oftrying
                to be all things to all people.</emphasizedText>
            <quote>
                <source>Walt Whitman</source>
                <quoteContent>Keep your face always toward the sunshine - and shadows will fall behind you.</quoteContent>
            </quote>
            <list ordered="true">
                <listItem>History</listItem>
                <listItem>Support</listItem>
            </list>
        </paragraph>
        <paragraph>
            <boldText>MARKUP FOR MUSIC</boldText>
            <emphasizedText>This problem is not unique to music applications. Demand forinteroperability among products from competing vendors has been thebane of the computer 
                industry since its birth. Fortunately, a solutionhas arisen from the world of Internet applications: the ExtensibleMarkup Language (XML). XML has emerged as 
                the accepted standard fordata representation and interchange among commercial software packages.Readers of EM are probably familiar with XML as it relates 
                toWeb pages (see “Mark My Words” in the November 2001 issue).But readers may not realize that XML has capabilities that reach farbeyond just souping up home
                pages.
                XML is a markup language for defining markup languages. It allowsyou to define a grammar for describing the data associated with anygroup or class of
                computer applications. When two programs want toshare data, they exchange a highly structured text document thatconforms to the syntax rules of XML and 
                the grammatical rules that thetwo programs have agreed upon.
                XML requires you to define your grammar in the form of another XMLdocument called a schema or a Document Type Definition (DTD). Byfollowing XML's rules 
                for creating a valid DTD, you don't need to worryabout how your grammar will be interpreted by a program. There arestandard tools for that, and that frees 
                you to focus on how to organizeand represent the data you want to share. This balance of flexibilityand consistency is the core strength of XML as a vehicle
                for datainterchange.</emphasizedText>
            <quote>
                <source>Mahatma Gandhi</source>
                <quoteContent>In a gentle way, you can shake the world.</quoteContent>
            </quote>
            <list ordered="false">
                <listItem>DTD</listItem>
                <listItem>XSD</listItem>
            </list>
            <boldText>Example</boldText>
            <emphasizedText>Like all XML-based formats, MusicXML is intended to be easy for automated tools to parse and manipulate. Though it is possible to create MusicXML
                by hand, interactive score writing programs like Finale and MuseScore greatly simplify the reading, writing, and modifying of MusicXML files. 
                The following example is a score consisting of a single whole note middle C in the key of C major on the Treble Clef.[16]</emphasizedText>

        </paragraph>
    </content>
</coverLetter>
